作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
print(np.linalg.inv(array1))
inv_array1=np.linalg.inv
if np.array_equal(inv_array1,np.identity(2))==True:
    print("array1 is an identity matrix")
else:
    print("array1 is not an identity matrix")

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
array1 is not an identity matrix


In [3]:
#2. 運用上列array計算特徵值、特徵向量?
eig=np.linalg.eig(array1)
print("eigenvalue :",eig[0])
print("eigenvector :",eig[1])

eigenvalue : [13.  2.]
eigenvector : [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))